### ISSUE TITLE
omegaconf.errors.ConfigKeyError

### ISSUE THREAD

**Issue by 001xiaolu** [jaryP/PixleAttack#1]
![003 1](https://user-images.githubusercontent.com/103937584/163899749-4cd8fa6f-f44d-4338-92ef-7a6c4893329b.jpg)
I've already encountered this problem twice. The first time was on line 81 of the main.py, and my solution was `OmegaConf.update(cfg, "training.devicces", 1, force_add=True) `to force the addition.When I continue to run it, I encountered this problem again.And there are many similar uses like `cfg['model']`  .
![003 2](https://user-images.githubusercontent.com/103937584/163900852-25f89717-cb1f-4f35-9b9b-ebe92d789b27.jpg)
Did I make a mistake in my configuration? Is there a fundamental solution?

**Comment by jaryP** [comment]
Hello there, seems like you are not giving a model name to train.

You can find working examples in the file experiments.sh, or, if you prefer, Pixle is not part of [TorchAttacks](https://github.com/Harry24k/adversarial-attacks-pytorch), "a PyTorch library that provides adversarial attacks to generate adversarial examples"

**Comment by 001xiaolu** [comment]
Thanks for your answer, I found the root of the problem.I have one more question.
`model_cfg = cfg['model']
 model_name = model_cfg['name']
 pre_trained = model_cfg.get('pretrained', False)`-----161 of the main.py
![004 1](https://user-images.githubusercontent.com/103937584/163983856-1eda1883-f864-4618-9199-9d3d1c5b6d1b.jpg)
There is only one parameter in the yaml file.Does this parameter 'pretrained' need me to add it manually?

**Comment by 001xiaolu** [comment]
![005 1](https://user-images.githubusercontent.com/103937584/163985388-77d1dab7-4cb3-42a6-a4be-e3caea72d4d5.jpg)
![005 2](https://user-images.githubusercontent.com/103937584/163985418-df1337b2-3948-45df-90cd-07cf8be7390b.jpg)
This is the result of my run, the two parameters in the small right corner have never changed.

**Comment by jaryP** [comment]
Try to play with the optimizer, because I used, for that specific case, SGD with LR set to 0.1 and momentum to 0.9
